# Generated by Django 3.2.20 on 2025-11-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magiclink', '0002_magiclinkunsubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='magiclinkunsubscribe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
